// LAPD bureau/division structure adapted to Los Santos (GTAW roleplay)
export const DIVISIONS = [
  // Central Bureau — Patrol
  "Central Division",
  "Rancho Division",
  "La Mesa Division",
  "Vinewood Division",
  "Davis Division",
  "Central Traffic Division",
  // South Bureau — Patrol
  "South Bureau Homicide Division",
  "Strawberry Division",
  "Davis South Division",
  "La Puerta Division",
  "Port Division",
  "South Traffic Division",
  // West Bureau — Patrol
  "Rockford Hills Division",
  "Vinewood West Division",
  "Del Perro Division",
  "Vespucci Division",
  "Pacific Division",
  "West Traffic Division",
  // Valley Bureau — Patrol
  "Sandy Shores Division",
  "Paleto Bay Division",
  "Grapeseed Division",
  "Harmony Division",
  "Valley Traffic Division",
  // Specialized Divisions
  "Metropolitan Division",
  "Robbery-Homicide Division",
  "Gang and Narcotics Division",
  "Detective Support & Vice Division",
  "Juvenile Division",
  "Commercial Crimes Division",
  "Major Crimes Division",
  "Emergency Services Division",
  "Air Support Division",
  "Transit Services Division",
  "Security Services Division",
  "Technical Investigation Division",
  "Forensic Science Division",
  // Administrative Divisions
  "Internal Affairs Division",
  "Force Investigation Division",
  "Training Division",
  "Communications Division",
  "Personnel Division",
  "Recruitment and Employment Division",
  "Information Technology Division",
  "Media Relations Division",
  "Risk Management & Legal Affairs Division",
  "Audit Division",
  "Records and Identification Division",
  "Evidence and Property Management Division",
  "Motor Transport Division",
  "Custody Services Division",
  "Facilities Management Division",
  // Bureaus
  "Central Bureau",
  "South Bureau",
  "West Bureau",
  "Valley Bureau",
  "Detective Bureau",
  "Transit Services Bureau",
  "Professional Standards Bureau",
  "Human Resources Bureau",
  "Training Bureau",
  "Information Technology Bureau",
  "Administrative Services Bureau",
  "Counterterrorism and Special Operations Bureau",
  "Community Safety Partnership Bureau",
] as const;
